name: hehe

on:
  schedule:
    - cron: '0 */5 * * *' 
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install scoop
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          scoop bucket add extras
          scoop bucket add versions
          scoop bucket add nirsoft
          scoop bucket add java
          scoop bucket add nonportable
          $env:SCOOP='~\scoop'
          echo "$env:SCOOP\shims" >> $env:GITHUB_PATH


      - name: sekop
        run: |
          scoop install git nodejs neofetch ffmpeg sox chromium
        
      - name: Sc
        run: git clone ${{ secrets.sc1 }}

      - name: npm
        run: |
          cd wa1
          npm install --force

      - name: run
        run: |
          cd wa1
          node ghact.js
